### ISSUE TITLE
Loss calculation error

### ISSUE THREAD

**Issue by iamtekson** [ashokdahal/RiskChanges#14]
Error is coming from spatial_overlay function: https://github.com/ashokdahal/RiskChanges/blob/master/RiskChanges/LossPG.py#L194

**Comment by ashokdahal** [comment]
> Error is coming from spatial_overlay function: https://github.com/ashokdahal/RiskChanges/blob/master/RiskChanges/LossPG.py#L194

can you provide with further detail on what is the error? is it because the EARtable is not loaded from database?

**Comment by iamtekson** [comment]
I didn't get any errors in my code. But somehow the code is skipping this operation and we are unable to get the aggregation result.

**Comment by ashokdahal** [comment]
this has been solved by using geopandas in calculation instead of use of postgis which caused more issues in different versions. the library no longer ureses postgis for spatial operations.
