### ISSUE TITLE
Small warning on exposure calculation

### ISSUE THREAD

**Issue by iamtekson** [ashokdahal/RiskChanges#16]
```
F:\SDSS\1. code\venv1\lib\site-packages\RiskChanges\RiskChangesOps\readraster.py:19: RuntimeWarning: 
Mean of empty slice.
  mean=intensity_data_classified[((intensity_data<threshold) & (intensity_data>=prev))].mean()       
F:\SDSS\1. code\venv1\lib\site-packages\numpy\core\_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```

**Comment by ashokdahal** [comment]
https://stackoverflow.com/questions/3767409/invalid-value-encountered-in-double-scalars-warning-possibly-numpy 

may be there was no value in some cases when we were calculating mean, I do not have solution in mind for calculating mean in cases where no intensity data is available. could you assign one of the intern to have a look at it later before it becomes error @iamtekson . for now it do not have any impact on calculation.

**Comment by iamtekson** [comment]
Yes sure. We can keep this error like this and will have a look later

**Comment by iamtekson** [comment]
I believe this issue is solved by a new way of classifying the raster.
