### ISSUE TITLE
Permission denied in saving _reclassified file

### ISSUE THREAD

**Issue by ashokdahal** [ashokdahal/RiskChanges#18]
#17 error with permission denied. @iamtekson 

this is because I do the classification of the hazard intensity map based on stepsize and base value during exposure calculation and it needs to save that raster to your data folder, do the python enviroment running it have enough persmission to save it? if it is created once, next time system auto overwrite the file, if it is problem in saving on the second time then just check if file with suffix _reclassified already exist and skip the part it reclassifies? creating this a isssue so we can fix later.

**Comment by iamtekson** [comment]
Yes sure. I agree with that. I checked and found that the reclassified raster file is already created there. We will come back to this issue later. It is fine I think.

**Comment by ashokdahal** [comment]
@iamtekson  i have added check for susceptibilty and if the file already exists or not. check if it solves your problem. otherwise it might be issue with permission on your enviroment.

**Comment by iamtekson** [comment]
I am on a windows machine. I don't know why this permission error is occurring.
