### ISSUE TITLE
In the aggregation result, "exposure_id", "loss_id" or "risk_id" column are missing

### ISSUE THREAD

**Issue by iamtekson** [ashokdahal/RiskChanges#32]
I checked the exposure aggregation table and found that the `exposure_id` column is missing there. Below is the ss,

![image](https://user-images.githubusercontent.com/39838116/128863254-34095284-9d98-4f82-a568-5dba059fc95b.png)

![image](https://user-images.githubusercontent.com/39838116/128863280-eb3b59c5-23b0-4e2a-b16d-a361262d4a3b.png)

**Comment by ashokdahal** [comment]
updated!
