### ISSUE TITLE
Reset password link doesn’t work. 

### ISSUE THREAD

**Issue by CeesVanWesten** [ashokdahal/RiskChanges#54]
I tried to log in with my e-mail: (c.j.vanwesten@utwente.nl) but didn’t know my password. I clicked the option: reset password. 
In the new window: Password Reset for SDSS , I entered my mail, and clicked submit. 

- Change the name: Password reset for SDSS. Into Password Reset for RiskChanges
- Give a clear message that the e-mail has been send after pressing submit. 

Why is there no option to send the password? Why should you make a new one when you have forgotten the old one? 
I received a mail with the following text: 
Click the following link to reset your password: http://localhost:3000//#/resetPasswordConfirm/?token=8eba405ed56235a31dc

Change this text to: 
Reset password for RiskChanges. 
Dear user. You have requested to change your password. 
Click the following link to reset your password: http://localhost:3000//#/resetPasswordConfirm/?token=8eba405ed56235a31dc

**Comment by iamtekson** [comment]
Solved the issue and replaced the old text with the suggested one.
