### ISSUE TITLE
Shape file doesn't upload

### ISSUE THREAD

**Issue by CeesVanWesten** [ashokdahal/RiskChanges#55]
[Buil_points.zip](https://github.com/RiskChanges/RiskChanges/files/8024144/Buil_points.zip)
The system cannot upload this file. The time bar is working when uploading, but then a message pops up for a few seconds with a lot of text, disappears, and the "busy" sign keeps displaying. 
This is a point file with building footprints, in a Zip file.

**Comment by iamtekson** [comment]
Solved!
