### ISSUE TITLE
Wind hazard map doesn't have the right metric

### ISSUE THREAD

**Issue by CeesVanWesten** [ashokdahal/RiskChanges#56]
When trying to upload the following map (wind_3000), which is a windspeed map for a return period of 3000 years, with wind speed in Km/h, it is not possible to select km/h as a Unit, when selecting Peak gust Velocity as Intensity. 
This problem occurs for many more combinations of Type and Intensity:
All heights (water, flood, tsunami etc) should also be in cm
All combinations should be checked

**Comment by iamtekson** [comment]
Solved. If you find any specific combination which is wrong. Please let me know I will fix it quickly.

**Comment by iamtekson** [comment]
https://docs.google.com/document/d/14FCTP582pj0lgULv4LCZX0DnCu-CArhJ/edit

**Comment by iamtekson** [comment]
I rechecked and corrected the things. Now it is exactly matching to our document.
