### ISSUE TITLE
Administrative units cannot be uploaded. 

### ISSUE THREAD

**Issue by CeesVanWesten** [ashokdahal/RiskChanges#57]
I get an error message when trying to upload the administrative units. An error message pops up a few seconds: 
![image](https://user-images.githubusercontent.com/76096946/152999131-2d065d38-bfe1-4cbd-8644-a3cf305cb838.png)
I think it has something to do with my organisation (University of Twente)
the problem is likely that a new user has made an organization and wants to upload data, but the database doesn't allow it?
[AdminUnits.zip](https://github.com/RiskChanges/RiskChanges/files/8024248/AdminUnits.zip)

**Comment by iamtekson** [comment]
Solved!
