### ISSUE TITLE
Visualisation of hazard maps doesn't work

### ISSUE THREAD

**Issue by CeesVanWesten** [ashokdahal/RiskChanges#59]
I tried to visualize several of the hazard maps that I uploaded in the system, such as a flood intensity map (flood height in meters), volcanic hazard map (susceptibility classes), landslide susceptibility map (classes). 
In the visualization window the legend doesn't show the classes, It also shows the map in one color only (black), or not at all,

**Comment by shakyaanice** [comment]
If the maps do not show, there might be an issue with the projection system.

**Comment by iamtekson** [comment]
I agree with @shakyaanice
