### ISSUE TITLE
Improvements in the display of lists of layers

### ISSUE THREAD

**Issue by CeesVanWesten** [ashokdahal/RiskChanges#63]
The way that lists of already available maps (e.g. uploaded elements-at-risk, hazard maps, exposure maps, loss maps, and risk maps) are shown can be improved. 

1. It would be much better if there would be a list that the user could scroll through (so with a scroll bar on the right) instead of with a fixed number of records.
2. The user should be able to change the order of the maps to make that more logical. So click on a record and move it up or down. So that a user can logically organize the data. Once done this order should be kept for the next time. 
3. The > and s.n. columns in the left are not relevant for the user. They should be left out. 
4. The columns could be spaced closer, leaving less open space in between, and perhaps also with a bit larger fontsize. 
5. When a user clicks on the header of a column, the width of this column increases so that it is possible to read all the text. 
6. The columns for hazard maps should be named as followed: **Name of Hazard Layer, Hazard Type, Hazard Intensity, Intensity Unit, Year, Alternative, Scenario, Date of uploading**. 
7. The title above should be:  **Available Hazard Layers**. 
8. The columns for the elements-at-risk should be: **Name of the Layer, Type, Year, Alternative, Scenario, Class column defined, Value data defined, Population data defined , Link to Vulnerability Curves**
9. The title above should be: **Available Elements-at-Risk (EaR) Layers**
10. The columns for vulnerability curves should be: Name of Vulnerability Curve, Type, Hazard Type, Hazard Intensity,EaR Risk type, EaR Class
11. The title above should be: **Available Vulnerability Curves**
12. The columns of Administrative Units are OK, but the edit button should be added here. 
13. The list of alternatives is OK, but the view and edit button should be added. the view button should display the document that was uploaded .
14. The title should be: **List of available Risk Reduction Planning Alternatives**
15. The list of scenarios is OK,  but the view and edit button should be added. the view button should display the document that was uploaded .
14. The title should be: **List of available Future Scenarios.**
15. In Exposure, the titles should be: **Available Elements-at-Risk layers**    and  **Available Hazard layers**
16. In the View already computed exposure layers, the title should be: Already computer exposure layers
17. The names of the columns in the already computed exposure layers should be: **Exposure Layer Name, Hazard Layer Name, Hazard Type, Return Period, Elements-at-Risk Layer Name,  Element-at-Risk Type, Year, Alternative, Scenario, Aggregation, Linked to Vulnerability curves,** 
18. The download data in the exposure part, should be changed to: Download Table, Download Map. In the second case a  shapefiles should be downloaded (either of the elements-at-risk layer, or the administrative unit layer , depending on the aggregation) where the column of the hazard classes are added together with the fraction . So if there are 1 hazard classes, there are also 10 columns added, plus the original columns that are in the table. 
19.  In the New Loss computation the column names should be: **Exposure Layer Name, Hazard Layer Name, Hazard Type, Return Period, Elements-at-Risk Layer Name,  Element-at-Risk Type, Year, Alternative, Scenario, Aggregation, Linked to Vulnerability curves,**

**Comment by iamtekson** [comment]
https://github.com/RiskChanges/riskchanges-frontend/issues/180

**Comment by iamtekson** [comment]
https://github.com/RiskChanges/riskchanges-frontend/issues/181

**Comment by iamtekson** [comment]
https://github.com/RiskChanges/riskchanges-frontend/issues/182

**Comment by iamtekson** [comment]
https://github.com/RiskChanges/riskchanges-frontend/issues/183

**Comment by iamtekson** [comment]
Most of the things are solved but some of the comments still need to solve. I created a new issue for those issues and I will work later to solve them. These are just secondary things.
