### ISSUE TITLE
Upload elements-at-risk from file

### ISSUE THREAD

**Issue by CeesVanWesten** [ashokdahal/RiskChanges#64]
Here are some improvements for this page:

1. Title should be: **Elements-at-Risk Layers**
2. **1: Upload data, 2: Enter metadata, 3: Which Columns to use? 4: Link to Vulnerability Curves**
3. The help text stops abruptly. 
4.  Improved help text: **Elements-at-Risk (EaR) can be in the form of Building Footprints, Land Parcels, Line features (e.g. roads, railways, powerlines), and Point data (e.g. schools, hospitals). The input data can be uploaded into the systems in three ways: as shapefiles uploaded by the user, by connection with OGC service (Open Geospatial Consortium, such as a Geonode ), and database connection. Before uploading the EaR files by the File upload option, make sure that these are projected in a proper coordinate system similar to the hazard layers. This can be done in GIS software such as ArcMap or QGIS. The user input file needs to be zipped which should contain the main format i.e. shapefile (.shp) along with other supporting extensions such as .shx,.prj,.dbf,.cpg,.sbn. Another important task is to check the EaR attributes in GIS software. The EaR should contain at least information on the Classes or Types of EaR. These will be used to link the classes with vulnerability curves. Also useful is to have a column with the Replacement Costs or Values in monetary terms, so that you can calculate later the risk in monetary terms as well. It is also useful to have a column with Population information if you also want to calculate population risk. ................................ EXPLAIN HOW TO USE THE OGC AND DATABASE CONNECTION COMPONENTS**............EXPLAIN THE 4 STEPS IN THE DATA ENTRY PROCEDURE AND WHAT SHOULD BE DONE IN EACH OF THESE STEPS.... 
5. Comments on the List of Available Elements-at-Risk Layers was given in the previous issue. 
6. The visualization part should contain the same functionalities as the main visualization, including an option to get the information at the mouse location when clicking. 
7. In the section on: Attribute Column Connection. Change the names: **Select the column that contains the classes of elements-at-risk**, It is not clear what the column Geometry is. It is added by the system, including another column with a code. Does geometry contain the Area of polygons or the length of line features? In that case, the column should be either called: Area(m2), Length(m), or Number. 
8. In the section on: Vulnerability Curve Connection, the selection that was made earlier disappears when you edit the file again. This should be fixed. Even more so, it should be possible to make more than one column with links to the vulnerability curve. For each hazard type, such link should be made. So when you first select to make the link for one type of hazard (e.g. Earthquake), the hazard name should appear above the list of selected vulnerability curves. Then you should be able to click on a + and a new list of links to curves appears, for which you also have to select the hazard type and intensity type. When you click on a curve it appears as a pop up window. So that you can put several of them next to each other. 
![image](https://user-images.githubusercontent.com/76096946/154270154-5f7767ce-68d2-4058-9938-304eca1f8c7f.png)
9. In the list of available elements-at-risk layers, the column _Linked to vulnerability curves_ is not properly updated. I made a connection to vulnerability curves, but it doesn't change in this column. Also the links to the vulnerability curves are not saved.

**Comment by iamtekson** [comment]
Solved!
