### ISSUE TITLE
Improve Hazard map input

### ISSUE THREAD

**Issue by CeesVanWesten** [ashokdahal/RiskChanges#65]
Would it not be best to make the entry of hazard data comparable to that of elements-at-risk data:
1: Upload data
2: Enter Metadata
3: Define classes
 

1 Upload data: 
- When uploading you should only upload the GeoTiff file or the link to OGC (this should be properly tested as I don't know how to do this, and I think it doesn't work.

2. Enter Metadata
- add:  **Hazard layer name**: provide a name for the hazard layer   (not clear what the asterisk means. Remove it), **Hazard Type** (drop-down list): , **Hazard Intensity Type** (dro[p-down list) , Hazard Intensity Unit ( drop-down list, but now there are a number of combinations for which no units can be selected , e.g. wind, peak gust velocity in km/h. The list of units for each of the intensity types should be carefully checked. Heights should always be in m, cm, mm, inches. Velocity in: m/s, km/h, miles/h, acceleration in : m/s2, g, gal, Beaufort scale is classes etc. ). 
- Return Period: (for the moment only one return period is enough. So remove the options min and max,)
- Risk reduction alternative
- Future scenario
- Representation year (future or current year)
Here it would be good to select the option NExt. 

3. Define Classes 
After pressing Next the system can then analyse the raster data. It would be great if a histogram could be shown, which would help the users to define the classes in the next stage
Here the user can the determine the following two components: 
- The intensity base value should be called: **Lowest Hazard Intensity threshold (values lowe than this are not considered as hazardous)**.  This should be an open field with the text "Enter value". The default should be 0. 
- The intensity interval should be called: **Hazard Intensity stepsize to consider**.  This should be an open field with the text "Enter value".  The default should be 1. 
- Also a new intensity value could be added: **Maximum intensity threshold (All higher values are one group)** . "Enter Values". Default is the maximum value in the raster map. 
-  After entering these two values, a Table is generated, with the classes indicated in the above three components. A column **Class Name** is made by combining the two values and the intensity unit. This column can be edited by the user if he wants to give different names:
![image](https://user-images.githubusercontent.com/76096946/154314345-13be837c-450e-4c37-919d-4ec3d4d9923a.png)
The user can also enter values for spatial probability

- in the case of a susceptibility map the procedure is almost the same. The table will look like: 
<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
The user can edit the class names and also enter the spatial probability values. 

![image](https://user-images.githubusercontent.com/76096946/154318294-2e020358-cea4-498a-aa36-3631b24fc356.png)

When you edit the hazard layer later all the things that were entered above should be displayed and can be changed by the user. 
You can then use:
The Class Name for the table of Exposure. 
The spatial probability in the loss calculation for both intensity maps and susceptibility maps
When we want to use the spatial probability values for different return periods in relation to susceptibility maps, the users has to upload the same susceptibility map several times, indicate the return period in step 2 and enter new spatial probability values in step 3.

**Comment by iamtekson** [comment]
Solved! I think now we can close this issue.
