### ISSUE TITLE
Improve exposure analysis

### ISSUE THREAD

**Issue by CeesVanWesten** [ashokdahal/RiskChanges#66]
The exposure analysis needs to be improved, because:
- the generation of Exposure ID files without a clear name is problematic for the user, e.g. when visualising
- the table output of exposure currently makes no sense to the user. 

I propose the following changes:

**Exposure Layer Name**. 
When the user selects a combination of an elements-at-risk layer and a hazard layer, the system should generate a new name for the exposure layer, which is the combination of elements-at-risk name, hazard type, return period, Alternative, scenario  and future year. It will do this by selecting fixed abbreviations: for example: LP_FLA_100_A0_S0_2022  (so the elements at risk types will have each an abbreviation (LP = Landparcels, BF=buildingfootprints, LI - Lines, PO = Points), and the hazard types as well .
See table below in section 1.1.2 (hazard ) from https://docs.google.com/document/d/14FCTP582pj0lgULv4LCZX0DnCu-CArhJ/edit?usp=sharing&ouid=114355974698561281693&rtpof=true&sd=true
This way the user will know better what each exposure layer means. Of course internally the exposure layers may have their own identifier, but the user will see the combination name. 

Use a **progress bar** when an exposure layer is calculated. Now it is quite unclear to the user what will happen after he presses the button to calculate exposure. Therefore a progress bar should be indicated for each exposure layer, so that it is also clear to the user if more exposure layers are selected, which ones are finished calculating. 

Once calculated, the user should go to the section: **View already computed exposure layers**. 
So here in the table, the Exposure Name should be added. the first three columns (checkboxes, > and s.n. ) can be removed. See my earlier comments on the suggested changes in the layer lists. 

Add in the right side: **Download table** and **Download map**. 
So the **Download map** is new: a shapefile is downloaded with either the original elements-at-risk and attributes, but now with additional columns for the exposure in the various hazard classes (best as fractions), See an example below for exposure of a building footprint map with a flood depth map (the classes in this map are derived from the hazard class definition when uploading the hazard map, such as minimum intensity to consider, intensity stepsize (0.5 m) in this case, the maximum intensity above which all will be one group, and the intensity metric (in this case m).  Note that the additional columns are also there such as Area, Value, and People, as indicated when uploading the elements-at-risk layer. 
![image](https://user-images.githubusercontent.com/76096946/154441552-643578bb-55fa-45da-afe7-3dd57d610156.png)
When the shapefile is downloaded, it is important to give it a name, similar to the **Exposure Layer Name** that I proposed above. This way user knows which shapefiles contains which results. It would be even better if metadata could be put in the shapefile, but I don't know if that is possible. 

When the user selects **Download table**, basically the same table as indicated above should be downloaded as CSV file, including the columns for the class name, Area/Length, Value, People, etc. The User can then calculate in Excel the absolute/relative exposure. The CSV file should be called with the same Exposure Layer Name as indicated above, 

If you select to **Query Exposure results** ,  a query window should appear, where the user can decide if he wants to show the exposure results in Area/length/number (the selection that is not valid is shown in grey and cannot be selected), Value (only if this has been selected in the uploaded elements-at-risk layer, otherwise shown as grey and cannot be selected) or Population (also only when a population column was selected in the EaR upload part, otherwise shown as grey). Each one would have a selection box. Only one can be selected. If the options are not available the selection is shown in grey and the box cannot be selected. Below it is the option to show the results as Relative or Absolute values. You can either show one of them. Relative values can be in fraction or in percentage. Then below is the option to display the results for individual elements-at-risk or for aggregation units (e.g. the administrative units). The option aggregate is shown in grey if there was no map selected for aggregation in the exposure definition. Then below is the option to make a selection of Elements-at-risk classes (a window appears where you can select all classes, or make a selection of specific elements-at-risk classes). Multiple classes can be selected. The system should then add up the values for all EaR of the same types within the same Admin Unit, or when not using admin units, make a selection of the EaR units to show. The next choice is to make a selection of which Hazard Classes should be shown. There the best is to use a slider, with the classes of the hazard indicated. The user can select to use the entire range, or make a selection. This selection is especially important when dis[playing the results in a map. It is also possible to use the option in the case the data is not aggregated. Then only the selected information will be shown in a table or map. The last and most important option is to visualize the results in a Table , a Map or both. when selection table , the results is shown in a pop-up window with the table. The table contains a right column: Result, which is the combined result of the query used in displaying the results in a map. 
 Below is an example of displaying the exposure as Area in Absolute values.  It is essential to keep the column indicating the ID's as the first column and the EaR classes as the second column
![image](https://user-images.githubusercontent.com/76096946/154493392-34c555c4-abb1-41d4-acf2-ed173339b27e.png)

The same approach can now  be followed when the exposure analysis is done using an Aggregation Layer.  The example below shows the case when we show the exposed Area, as absolute values, grouped by the Administrative Units. the starting column should always be the Admin units in this case. 

![image](https://user-images.githubusercontent.com/76096946/154478218-afa09650-57f9-496c-9459-d9e30b51b2f4.png)

The same procedure should also work when you don't have a hazard intensity map, but a susceptibility map. In that case also the classes have been defined in the hazard upload section. The example below shows the relative exposure of population at individual EaR level for a land parcel map and a landslide susceptibility map. 
![image](https://user-images.githubusercontent.com/76096946/154481608-f544e60c-78c6-4d88-bb4e-8e0cc5774709.png)

The example below shows the same results but now as absolute population exposure only for residential area, and for the classes from moderate to very high. 
![image](https://user-images.githubusercontent.com/76096946/154481423-85ee885a-eb2c-407a-9854-0fac87b7bcfc.png)

Displaying exposure results as maps should be easier. The Query Exposure Data window can be a pop-up in the visualization window (or added to a fixed part e.g. in the bottom right part). Based on the result of the query a table window is opened (if the users selects to see the results as table) and the visualization style of the Result of the query (so how to display the column Result from the query) is shown in the upper right , where the user can select the column, the colour scale (I recommend to have a default scale from green low values via yellow to orange and red). In the bottom right the legend should appear and also the option to sho the metadata of the resulting query.
![image](https://user-images.githubusercontent.com/76096946/154492992-f2121669-84ac-43ae-8a52-48c49fa27c87.png)

Finally, here is an example that displays the results of the query with absolute value of exposed area aggregated by AdminUnits. The aggregated exposure results by adminunits should be stored in the attribute table of the AdminUnits as well, so that you can display one value per Admin unit. 

![image](https://user-images.githubusercontent.com/76096946/154496097-f4900c3d-17d1-48df-8a65-2ca054818bac.png)

I hope this is all possible to implement.

**Comment by iamtekson** [comment]
Solved.
