### ISSUE TITLE
WMS layer not uploaded

### ISSUE THREAD

**Issue by shakyaanice** [ashokdahal/RiskChanges#68]
The layers are displayed in the QGIS but not in the RiskChanges app.
Check with following URLS: 
https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi
https://www.riskinfo.lk/layers/riskinfo_data:geonode:Final_Buildings_Remuna_GND_650

**Comment by iamtekson** [comment]
solved. Need to investigate further for visualization of the data.
