### ISSUE TITLE
Value and population exposure need to implement

### ISSUE THREAD

**Issue by iamtekson** [ashokdahal/RiskChanges#75]
In the current implementation, on `getSummary` function of exposure, we are calculating the summary based on `areaOrLenght`, Need to implement the following things as well,

1. Exposure based on population and value
2. I think our current implementation is the absolute value but needs to implement the relative exposure as well

**Comment by ashokdahal** [comment]
it is done also the exposure is fixed to always have these values as well as admin id. @iamtekson please make it compulsory from GUI to have admin_PK column defined (or random generation?) otherwise it will not be possible to perform any analysis because we won't be able to aggregate in any sense.

**Comment by iamtekson** [comment]
Yes, I already implemented it. Thanks!
